### ISSUE TITLE
Normal underground pipe can be connected to big ducts

### ISSUE THREAD

**Issue by KermitEmperor** [raiguard/FluidMustFlow#13]
### Description

![image](https://user-images.githubusercontent.com/74988196/236561941-33491951-d3c7-4de8-8e5a-027f2cb740cf.png)
![image](https://user-images.githubusercontent.com/74988196/236562074-53ebf927-56db-4117-b18a-1a110cfdc0a3.png)

### Reproduction

1. place almost any kind of duct (we gonna use straight duct)
2. place a normal underground in this way:
![image](https://user-images.githubusercontent.com/74988196/236562454-dd7862b2-441f-466e-aaaa-eae8c8d9d460.png)
3. Profit

![image](https://user-images.githubusercontent.com/74988196/236562487-01aa848b-40ab-4802-bff5-ef74d3c6ffeb.png)

**Comment by KermitEmperor** [comment]
Also, this can also be done with a junction

**Comment by raiguard** [comment]
Congratulations!!! You have discovered a bug in the Factorio engine. I will add this to my todo list and take a look sometime soon.

**Comment by raiguard** [comment]
False alarm: this is not a bug. Turns out that all of the ducts had `max_underground_distance = 1` for some reason, which was causing all of these problems.

Fixed for the next release.
