### ISSUE TITLE
Underground Ducts

### ISSUE THREAD

**Issue by Delta4Phoenix** [raiguard/FluidMustFlow#14]
### Description

I cannot place Underground ducts adjacent to any other duct, I need to put at least one 'small' duct in between
![image](https://user-images.githubusercontent.com/36764081/236948844-0db9a325-4bed-4aaf-88a3-c0b66e34c5ba.png)
![image](https://user-images.githubusercontent.com/36764081/236951169-58ae1a55-10cb-4483-ba12-65854e5bee19.png)

**Comment by SuperPyroManiac** [comment]
To add on to this, they cannot be placed against any other ducts. I've noticed I CAN place them first, then the other pipe/pump and it fits.

https://i.imgur.com/wbUFcid.png
https://i.imgur.com/YoHvm6O.png
