### ISSUE TITLE
Underground ducts connecting to underground regular pipes?

### ISSUE THREAD

**Issue by teshiron** [raiguard/FluidMustFlow#19]
Is it expected behavior that underground ducts can interfere with/connect to underground pipes?  I've noticed that I placed an underground duct on either side of an area that had a regular underground pipe in the middle, and the duct sucked out most of the fluid in that system and shot in what was in the duct (without any warning about fluid system interconnection, either).

**Comment by raiguard** [comment]
This is unfortunately unavoidable in Factorio 1.1. Once Factorio 2.0 is released I will be able to fix it.
