### ISSUE TITLE
Duct exhaust ports cause "cannot connect systems with different fluids" when two are butted together

### ISSUE THREAD

**Issue by SReject** [raiguard/FluidMustFlow#21]
### Description

If you have two fluid systems and butt a Duct Exhaust from each system against each other, it causes "Cannot connect systems with different fluids" issues

### Reproduction

![image](https://github.com/raiguard/FluidMustFlow/assets/1975663/45d176bd-8633-4ce3-9874-de407ee1ff35)

Note that attempting to connect the Small straight duct to a system not containing water results in the "Cannot connect systems with different fluids" issue.

**Comment by raiguard** [comment]
This is a base game bug. It has been fixed for Factorio 2.0.
