### ISSUE TITLE
Duct connect with underground pipe. 

### ISSUE THREAD

**Issue by some0nenew** [raiguard/FluidMustFlow#24]
### Description

When i place Ducts and underground pipes in line the SOMETIMES connect, i have not figured out yet when or why, it feels like it can change at random, because i remember that i needed to fix systems that worked flawlessly before. 

No matter what i tried i could not separate these two:
![image](https://github.com/raiguard/FluidMustFlow/assets/87366654/e6e2895e-0710-48c3-a300-2926ce1c93da)
These on the other hand work fine:
![image](https://github.com/raiguard/FluidMustFlow/assets/87366654/5bd7a208-f700-4a7c-b380-d439af8a7227)
There are several like this up and down
![image](https://github.com/raiguard/FluidMustFlow/assets/87366654/4766bad0-9c27-494e-a6e5-ad44ed311fe5)

I noticed that it often works if i just nudge them into place with picker dollies. But even this did not fix Pic 1.

If there are any other open questions just ask, but hopefully i included all necessary information.

### Reproduction

Load save [https://privatenextcloud.ddns.net/nextcloud/index.php/s/QGjT9q8Lt4pAprg, Valid till 1.Feb]
I marked the 3 Pictures i took on the map, Yellow exclamation mark, "Pic x"

**Comment by Wolvereness** [comment]
![image](https://github.com/raiguard/FluidMustFlow/assets/983111/4a5756a3-0d4f-4ea4-8a0c-c5eb0fbe7b12)

This one just caught me today. Just southwest of this is another case going left-right.

https://1drv.ms/u/s!Ainuapce_TfgmyxKN0SzP99dUvm-?e=VJuP68 - save file

**Comment by raiguard** [comment]
This is unfixable in Factorio 1.1, but will be fixed for Factorio 2.0.
