### ISSUE TITLE
pY compatibility

### ISSUE THREAD

**Issue by protocol-1903** [raiguard/FluidMustFlow#25]
A few notes on compatibility with pY.

As is, the 'Ducts' technology requires chemical science, most likely due to the vanilla game not having many fluids until then. Using pY, this is not the case, and the tech requirements are vastly overcomplicated for a bunch of pipes. It would make sense if they were changed to Logistic Science or pY1 if not Automation science.
![image](https://github.com/raiguard/FluidMustFlow/assets/67478786/a69ad809-02dd-430d-9949-ba507342267b)

The underground distance closely matches the Niobium pipes unlocked in logistics science, so I'm using those to compare. The current ducts do not require many resources to make, and as such seem like a cheap option, especially with higher tier pipes in the tech tree. It would make sense for them to require more iron, steel, and other components. Possibly use steel to craft the ducts instead of iron.

**Comment by raiguard** [comment]
I will leave this to the pY devs to solve, they know better than I on what is a good balance.
