### ISSUE TITLE
Space Age Support

### ISSUE THREAD

**Issue by bior12** [raiguard/FluidMustFlow#27]
### Description

Hey, this isn't a bug, but is there any idea of when the space age expansion will be supported? Thanks!

**Comment by raiguard** [comment]
I've had the mod ported to 2.0 for a year, but the question is... is it useful? Pipes in 2.0 have effectively limitless throughput.

I will probably update it just for the heck of it, but I don't imagine the mod playing a useful role in builds any more.

**Comment by bior12** [comment]
Ah ok, thanks for the replay and forgive my ignorance on that part (havent had a lot of time to look into all the mew features of the dlc), I had started a world a little while ago in preparation with the space age dlc, which uses mods like this one and a few others (which in hindsight probably wasnt the best idea), and was just hoping to use my old world to continue playing into the dlc, but thanks for the update!
