### ISSUE TITLE
Compatibility with NPT

### ISSUE THREAD

**Issue by protocol-1903** [raiguard/FluidMustFlow#30]
### Description

Hey, is it possible that you could add some information to your pipe-to-ground so that NPT can support it fully? As of now (or rather whenever I push the next update) it will connect to basic pipe to grounds, I'd like it to just connect to the special underground ducts.

If you don't mind adding compatibility, I would prefer it look something like this:
`duct_to_ground.npt_compat = { mod = "fluid-must-flow" }`
The string inside mod can be whatever, just let me know what it is so I know what to look for.

Thanks!

**Comment by raiguard** [comment]
What is NPT?

**Comment by protocol-1903** [comment]
https://mods.factorio.com/mod/no-pipe-touching?from=search

My mod that prevents pipes of the same type from connecting to each other.
You can ignore this, I added the compat on my end.
