### ISSUE TITLE
[1.4.0] Tungsten pipelining not unlocking

### ISSUE THREAD

**Issue by Andargor** [raiguard/FluidMustFlow#31]
### Description

Tungsten pipelining does not unlock when chimney vents are mined.

FluidMustFlow 1.4.0
Maraxsis 1.19.5

Video: https://www.youtube.com/watch?v=jON95tcYNzY

Multiplayer game

Will cross-post to Maraxsis in case it's a compatibility issue

EDIT: Cross-post https://github.com/notnotmelon/maraxsis/issues/44

### Reproduction

1. Mine chimney vent

**Comment by raiguard** [comment]
This was a maraxsis bug.
