### ISSUE TITLE
[question] have you a compatibility (or same feature) than "better thermal pipe"

### ISSUE THREAD

**Issue by Fr-Dae** [raiguard/FluidMustFlow#37]
"Pipes containing hot fluid will not freeze."
          https://mods.factorio.com/mod/better-thermal

**Comment by raiguard** [comment]
I will leave it up to the author of that mod to add compatibility for FMF.

**Comment by Fr-Dae** [comment]
bigJ don't know how to use github, so the process it's way more slow than you on github here :/
