### ISSUE TITLE
Underground ducts do not reliably connect when obstructed 

### ISSUE THREAD

**Issue by WildBraas** [raiguard/FluidMustFlow#6]
### Description

In pic all underground pipes is not connected with its pair, so its weird
![2022-03-12_14-39-49](https://user-images.githubusercontent.com/5339915/158016643-1e771f06-2018-4e60-beaa-832a008bfa86.png)

### Reproduction

If build as in pic, underground pipes will not linked with its pair

### Factorio version

1.1.55

### In-game username

Wild Braas

**Comment by raiguard** [comment]
The plot thickens...

The game engine was never intended to support pipes that were larger than 1x1. Consequently, there are a few issues like this. It's up to the Factorio devs to fix them, but I wouldn't hold my breath.

**Comment by raiguard** [comment]
Sourcehut ticket: https://todo.sr.ht/~raiguard/factorio-mods/8

**Comment by raiguard** [comment]
Closing as there is nothing I can do about this.

**Comment by raiguard** [comment]
Good news: I figured this out. It's not a bug in the game at all, it was the mod! The duct fluidboxes had `max_underground_length = 1`, which was causing all sorts of havoc.

Fixed for the next release.
